title: Lucas Palmer
description: UX Research · Cognitive Psychology
theme: minima

url: "https://lucaspalmer1.github.io"   # your user domain
baseurl: "/lucaspalmer"                 # your project path

minima:
  nav_pages:
    - publications.md
    - presentations.md
