title: Lucas Palmer
description: UX Research · Cognitive Psychology
theme: minima

# ---- required for project sites ----
url: "https://lucaspalmer1.github.io"
baseurl: "/lucaspalmer"

# ---- navigation ----
minima:
  nav_pages:
    - publications.md
    - presentations.md
